/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.FRimoveis.telas;

import br.com.FRimoveis.Conexao.ConexaoBD;
import br.com.FRimoveis.dao.CadastroContratoDB;
import br.com.FRimoveis.dao.CadastroImoveisDB;
import br.com.FRimoveis.dao.CadastroPessoasDB;
import br.com.FRimoveis.dao.ConsultaContratoDB;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigolima
 */
public final class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conexao = new ConexaoBD();
    CadastroImoveisDB cadastroImoveisDB = new CadastroImoveisDB();
    CadastroPessoasDB cadastroPessoasDB = new CadastroPessoasDB();
    CadastroContratoDB cadastroContratoDB = new CadastroContratoDB();
    TelaLogin login = new TelaLogin();
    TelaCadastroImoveis cadastroImoveis = new TelaCadastroImoveis();
    TelaCadastroPessoas cadastropessoa = new TelaCadastroPessoas();
    TelaCadastroUsuarios cadastrousuario = new TelaCadastroUsuarios();
    TelaConsultarContrato telaConsultar = new TelaConsultarContrato();
    TelaEmailAnexo emailAnexo = new TelaEmailAnexo();
    TelaGerarRecibo telarecibo = new TelaGerarRecibo();
    TelaGerarContrato contrato = new TelaGerarContrato();
    TelaFaleConosco faleconosco = new TelaFaleConosco();
    TelaSobre sobre = new TelaSobre();

    /**
     * Creates new form TelaInical
     */
    public TelaPrincipal() {
        initComponents();
        setIcon();
        login.dispose();
        validarContratos();
    }

    public void validarContratos() {
        ConsultaContratoDB consultar = new ConsultaContratoDB();
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("yyyy-MM-dd");
        consultar.verificarContratos(formatarDate.format(data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuPessoas = new javax.swing.JMenuItem();
        menuImoveis = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuContratos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuFinanceiro = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        menuRelClientes = new javax.swing.JMenuItem();
        menuRelImoveis = new javax.swing.JMenuItem();
        menuRelContratos = new javax.swing.JMenuItem();
        menuRecibo = new javax.swing.JMenu();
        MenuGerarRecibo = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuFaleConosco = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FR - Gerenciador de Imoveis");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(24, 768));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/FRimoveis/icones/Principal_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        menuCadastro.setText("Cadastro");
        menuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        menuPessoas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuPessoas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuPessoas.setText("Clientes");
        menuPessoas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoasActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPessoas);

        menuImoveis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        menuImoveis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuImoveis.setText("Imoveis");
        menuImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImoveisActionPerformed(evt);
            }
        });
        menuCadastro.add(menuImoveis);

        menuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menuUsuarios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios.setEnabled(false);
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuUsuarios);

        jMenuBar1.add(menuCadastro);

        menuContratos.setText("Contratos");
        menuContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuContratos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem1.setText("Gerar Contrato");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuContratos.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem3.setText("Consultar Contrato");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuContratos.add(jMenuItem3);

        jMenuBar1.add(menuContratos);

        menuFinanceiro.setText("Financiero");
        menuFinanceiro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuBar1.add(menuFinanceiro);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorios.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        menuRelClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuRelClientes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuRelClientes.setText("Clientes");
        menuRelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRelClientesMouseClicked(evt);
            }
        });
        menuRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelClientesActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelClientes);

        menuRelImoveis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menuRelImoveis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuRelImoveis.setText("Imoveis");
        menuRelImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelImoveisActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelImoveis);

        menuRelContratos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuRelContratos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menuRelContratos.setText("Contratos");
        menuRelContratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelContratosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelContratos);

        jMenuBar1.add(menuRelatorios);

        menuRecibo.setText("Recibo");
        menuRecibo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRecibo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        MenuGerarRecibo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        MenuGerarRecibo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuGerarRecibo.setText("Gerar Recibo");
        MenuGerarRecibo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuGerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGerarReciboActionPerformed(evt);
            }
        });
        menuRecibo.add(MenuGerarRecibo);

        jMenuBar1.add(menuRecibo);

        menuOpcoes.setText("Opções");
        menuOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuOpcoes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem2.setText("Enviar Anexo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuOpcoes.add(jMenuItem2);

        MenuFaleConosco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        MenuFaleConosco.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuFaleConosco.setText("Fale Conosco");
        MenuFaleConosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFaleConoscoActionPerformed(evt);
            }
        });
        menuOpcoes.add(MenuFaleConosco);

        MenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuSair.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(MenuSair);

        jMenuBar1.add(menuOpcoes);

        menuAjuda.setText("Ajuda");
        menuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAjuda.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem9.setText("Sobre");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem9);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(970, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoasActionPerformed
        if (!cadastropessoa.isVisible()) {
            cadastropessoa.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
    }//GEN-LAST:event_menuPessoasActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Quer Sair do Sistema?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuSairActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        if (!cadastrousuario.isVisible()) {
            cadastrousuario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImoveisActionPerformed
        if (!cadastroImoveis.isVisible()) {
            cadastroImoveis.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
    }//GEN-LAST:event_menuImoveisActionPerformed
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (!telaConsultar.isVisible()) {
            telaConsultar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuRelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRelClientesMouseClicked
    }//GEN-LAST:event_menuRelClientesMouseClicked

    private void menuRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelClientesActionPerformed
        try {
            cadastroPessoasDB.imprimirRelatorio();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRelClientesActionPerformed

    private void menuRelImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelImoveisActionPerformed
        try {
            cadastroImoveisDB.imprimirRelatorio();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRelImoveisActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (!contrato.isVisible()) {
            contrato.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (!sobre.isVisible()) {
            sobre.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void MenuFaleConoscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFaleConoscoActionPerformed
        if (!faleconosco.isVisible()) {
            faleconosco.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFaleConoscoActionPerformed

    private void menuRelContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelContratosActionPerformed
        try {
            cadastroContratoDB.imprimirRelatorio();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRelContratosActionPerformed

    private void MenuGerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGerarReciboActionPerformed
        if (!telarecibo.isVisible()) {
            telarecibo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuGerarReciboActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (!emailAnexo.isVisible()) {
            emailAnexo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tela já esta aberta!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IconeSistema/IconeSistema.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuFaleConosco;
    private javax.swing.JMenuItem MenuGerarRecibo;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    public static javax.swing.JMenu menuContratos;
    public static javax.swing.JMenu menuFinanceiro;
    public static javax.swing.JMenuItem menuImoveis;
    private javax.swing.JMenu menuOpcoes;
    public static javax.swing.JMenuItem menuPessoas;
    public static javax.swing.JMenu menuRecibo;
    private javax.swing.JMenuItem menuRelClientes;
    private javax.swing.JMenuItem menuRelContratos;
    private javax.swing.JMenuItem menuRelImoveis;
    public static javax.swing.JMenu menuRelatorios;
    public static javax.swing.JMenuItem menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
